### ISSUE TITLE
Error while using with aiohttp

### ISSUE THREAD

**Issue by vitalerter** [eht16/python-logstash-async#53]
Hi i several times get this error:

`base_events.py,base_events,default_exception_handler,ERROR,6,LogProcessingWorker,Task exception was never retrieved,
future: <Task finished coro=<Client._misc_loop() done, defined at /usr/local/lib/python3.7/site-packages/asyncio_mqtt/client.py:309> exception=CancelledError()>,
concurrent.futures._base.CancelledError`

After this error the logstash not sending data to Elastic.

How to solve this?
Thanks

**Comment by eht16** [comment]
Can you provide more information?
This library does not use `aiohttp` at all and I cannot see any relevance in the above error.

**Comment by vitalerter** [comment]
Hi, i use "python-logstash-async " library in my project in order to log data to elastic
My configurations:

```
logstash_formatter:
            (): logstash_async.handler.LogstashFormatter
            tags:
                - localhost
            extra:
                index_name: <index>
logstash:
            level: DEBUG
            class: logstash_async.handler.AsynchronousLogstashHandler
            formatter: logstash_formatter
            host: <host>
            port: <port>
            database_path: 
```
Sometime i get an error, then logstash_async stop working.

`base_events.py,base_events,default_exception_handler,ERROR,6,LogProcessingWorker,Task exception was never retrieved, future: <Task finished coro=<Client._misc_loop() done, defined at /usr/local/lib/python3.7/site-packages/asyncio_mqtt/client.py:309> exception=CancelledError()>, concurrent.futures._base.CancelledError`
